# Use official Python image
FROM python:3.11-slim

WORKDIR /app

COPY src/fleet_simulator.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

CMD ["python", "fleet_simulator.py"]